title: "Coding Practicum"
author: Nathan Bailey
description: Coding Practicum is a capstone course intended to provide you with the opportunity to apply the skills and knowledge learned in previous Coding courses toward the completion of an in-depth project with fellow team members.
url: https://c1.tribebytes.com

remote_theme: dnbailey/coursepack@main

collections:
  units:
    output: true
    permalink: /:path/
    layout: unit

defaults:
  - scope:
      type: "units"
    values:
      layout: "unit"

exclude:
  - LICENSE
  - README.md
